[2025-08-19T22:07:44.160+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T22:07:44.228+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_to_db manual__2025-08-19T22:04:36.409499+00:00 [queued]>
[2025-08-19T22:07:44.249+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_to_db manual__2025-08-19T22:04:36.409499+00:00 [queued]>
[2025-08-19T22:07:44.250+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-19T22:07:44.278+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_db> on 2025-08-19 22:04:36.409499+00:00
[2025-08-19T22:07:44.292+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_to_db', 'manual__2025-08-19T22:04:36.409499+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpn0hqd1fa']
[2025-08-19T22:07:44.296+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask load_to_db
[2025-08-19T22:07:44.296+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1632) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-19T22:07:44.298+0000] {standard_task_runner.py:64} INFO - Started process 1634 to run task
[2025-08-19T22:07:44.368+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.load_to_db manual__2025-08-19T22:04:36.409499+00:00 [running]> on host cb7c185c195d
[2025-08-19T22:07:44.516+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_to_db' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T22:04:36.409499+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T22:04:36.409499+00:00'
[2025-08-19T22:07:44.519+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T22:07:44.538+0000] {load_to_db.py:13} INFO - Reading Parquet file from ../data/products_cleaned.parquet
[2025-08-19T22:07:44.548+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T22:07:44.549+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 17, in load_task
    load_to_db()
  File "/opt/airflow/etl/load_to_db.py", line 14, in load_to_db
    df = pl.read_parquet(parquet_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 128, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 128, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/polars/io/parquet/functions.py", line 289, in read_parquet
    return lf.collect()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 97, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/polars/lazyframe/opt_flags.py", line 330, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2335, in collect
    return wrap_df(ldf.collect(engine, callback))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No such file or directory (os error 2): ../data/products_cleaned.parquet

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

[2025-08-19T22:07:44.596+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=load_to_db, run_id=manual__2025-08-19T22:04:36.409499+00:00, execution_date=20250819T220436, start_date=20250819T220744, end_date=20250819T220744
[2025-08-19T22:07:44.622+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task load_to_db (No such file or directory (os error 2): ../data/products_cleaned.parquet

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'
; 1634)
[2025-08-19T22:07:44.674+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-19T22:07:44.715+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-19T22:07:44.719+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
